package com.elavon.converge.model;

/**
 * Created by dennis on 10/24/17.
 */

public class ElavonError {
    private static final int CODE_GATEWAY_NOT_RESPONDING = 3000;
    private static final int CODE_GATEWAY_GENERATED_ERROR = 3001;
    private static final int CODE_ADAPTER_GENERATED_ERROR = 3002;

    private static final int CODE_VID_NOT_SUPPORTED = 4000; // Converge ID not supplied in auth request
    private static final int CODE_HTTP_NOT_ALLOWED = 4002; // HTTP POST not allowed for this account
    private static final int CODE_HTTP_REFERRER_INVALID = 4003;
    private static final int CODE_EMAIL_ADDRESS_INVALID = 4005;
    private static final int CODE_CVV2_NOT_REQUESTED_WITH_DATA = 4006; // CVV2 indicator was not identified in the authorization request
    private static final int CODE_CVV2_REQUESTED_BUT_NO_DATA = 4007; // CVV2 check cannot be performed as no data was supplied in the authorization request.
    private static final int CODE_REQUIRED_FIELD_NOT_SUPPLIED = 4009;
    private static final int CODE_INVALID_TRANSACTION_TYPE = 4010;
    private static final int CODE_RECEIPT_URL_MISSING = 4011;
    private static final int CODE_PIN_NOT_SUPPORTED = 4013;
    private static final int CODE_NOT_PERMITTED = 4014; // This terminal or user ID is not permitted to process this transaction type.
    private static final int CODE_PERMISSION_DENIED = 4016;
    private static final int CODE_TIME_OUT = 4017; // The request has timed out. The allotted time to complete the request has ended. Please try again.
    private static final int CODE_SETTLEMENT_IN_PROGRESS = 4018; // Settlemet in progress, VOID failed
    private static final int CODE_USER_ID_NOT_SUPPLIED = 4019; // The User ID was not supplied in the authorization request.
    private static final int CODE_SYSTEM_UNAVAILABLE = 4022; // The system is unavailable. This transaction request has not been approved. Please try again later.
    private static final int CODE_SETTLEMENT_NOT_ALLOWED_FOR_TERMINAL = 4023;
    private static final int CODE_INVALID_CREDENTIALS = 4025; // The credentials supplied in the authorization request are invalid.

    private static final int CODE_CREDIT_CARD_NUMBER_INVALID = 5000; // The Credit Card Number supplied in the authorization request appears to be invalid.
    private static final int CODE_EXPIRY_DATE_INVALID = 5001;
    private static final int CODE_AMOUNT_INVALID = 5002;
    private static final int CODE_APPROVAL_CODE_NO_FORCE = 5003; // A FORCE Approval Code was supplied for this transaction, however the transaction type is not FORCE
    private static final int CODE_INVALID_APPROVAL_CODE = 5004; // The FORCE Approval Code supplied in the authorization request
        // appears to be invalid or blank. The FORCE Approval Code must be 6 or less alphanumeric characters

    private static final int CODE_FIELD_CHARACTER_LIMIT_EXCEEDED = 5005;
    private static final int CODE_REFUND_AMOUNT_EXCEEDS_LIMIT = 5006;
    private static final int CODE_SALES_TAX_INVALID = 5007;
    private static final int CODE_INVALID_ACCOUNT_TYPE = 5008; // This PINLess Debit Transaction contains invalid account type. Account type can be checking or saving.
    private static final int CODE_INVALID_SURCHARGE_AMOUNT = 5009; // Invalid Surcharge amount for the PIN less debit transaction.
    private static final int CODE_INVALID_EGC_TRANSACTION_TYPE = 5010; // electronic gift certificate?
    private static final int CODE_INVALID_EGC_TENDER_TYPE = 5011;
    private static final int CODE_INVALID_TRACK2_DATA = 5012;
    private static final int CODE_TRACK2_DATA_REQUIRED = 5013;
    private static final int CODE_PIN_MISSING = 5014;
    private static final int CODE_INVALID_VOUCHER_NUMBER = 5015; // ssl_voucher_number must be 15 digits and numeric
    private static final int CODE_INVALID_MICR_DATA = 5016;
    private static final int CODE_MICR_DATA_AND_IMAGE_MISMATCH = 5017; // The image uploaded doesn’t match the MICR data sent for that check.
    private static final int CODE_MISSING_MAC_VALUE = 5018;
    private static final int CODE_MIN_LENGTH_ERROR = 5019; // Minimum Field Character Limit not reached
    private static final int CODE_INVALID_FIELD = 5020; // The Field does not apply to this transaction type.
    private static final int CODE_INVALID_CVV2_VALUE = 5021; // The value for the CVV2 (ssl_cvv2cvc2) field should be 3 or 4 digits in length. This value must be numeric.
    private static final int CODE_INVALID_CVV2_INDICATOR_VALUE = 5022; // The value for the C V V 2 indicator (ssl_cvv2cvc2_indicator) field should be 1 Numeric Character only. Validvalues are: 0, 1, 2, 9.
    private static final int CODE_INVALID_CARD_PRESENT_INDICATOR = 5023;
    private static final int CODE_CASHBACK_AMOUNT_INVALID = 5024;
    private static final int CODE_INVALID_KEY_POINTER = 5025; // The value for the key pointer (ssl_key_pointer) field should be 1 Character only. Valid value is: T for Triple-DES DUKPT.
    private static final int CODE_INVALID_BILLING_CYCLE = 5030;
    private static final int CODE_INVALID_PAYMENT_DATA = 5031; // The next payment date specified is not a valid entry.
    private static final int CODE_INVALID_INSTALLMENT_NUMBER = 5032;
    private static final int CODE_INVALID_RECURRING_ID = 5033;
    private static final int CODE_INVALID_INSTALLMENT_ID = 5034;
    private static final int CODE_RECURRING_LIMIT_EXCEEDED = 5035;
    private static final int CODE_INSTALLMENT_PAYMENTS_COMPLETED = 5036;
    private static final int CODE_INVALID_END_OF_MONTH_VALUE = 5037;
    private static final int CODE_INVALID_HALF_OF_MONTH_VALUE = 5038;
    private static final int CODE_HALF_OF_MONTH_AND_NEXT_PAYMENT_DATE_COMBINATION_MISMATCH = 5039; // The half of the month value provided [value] doesn’t correspond with the next payment date of [value].
    private static final int CODE_INVALID_TRANSACTION_ID = 5040;
    private static final int CODE_EXCEEDED_THE_10_MINUTES_WINDOW = 5041; // Unable to void transaction, exceeds the 10 min window.
    private static final int CODE_SWIPE_DATA_IS_NOT_ALLOWED_FOR_THIS_MARKET_SEGMENT = 5042;
    private static final int CODE_END_OF_MONTH_AND_NEXT_PAYMENT_DATE_COMBINATION_MISMATCH = 5043;
    private static final int CODE_INVALID_TIP = 5050;
    private static final int CODE_MISSING_RESPONSE_FILE_NAME = 5055;
    private static final int CODE_INVALID_RESPONSE_FILE_NAME = 5056; // The response file name is invalid. Please make sure the response file name doesn’t contain any of thecharacters : \ / : * ? “ < > |
    private static final int CODE_MISSING_BATCH_FILE = 5057;
    private static final int CODE_INVALID_BATCH_FILE_NAME = 5058;
    private static final int CODE_INVALID_BATCH_FILE_FORMAT = 5059;
    private static final int CODE_INVALID_BATCH_FILE_EXTENSION = 5060;
    private static final int CODE_IMPORT_BATCH_IN_PROGRESS_RETRY_LATER = 5061;
    private static final int CODE_FILE_EXCEEDS_MAX_NUMBER_OF_TRANSACTIONS = 5062;
    private static final int CODE_FILE_ALREADY_IMPORTED = 5063;
    private static final int CODE_INVALID_FIELDS_IN_BATCH_FILE = 5064;
    private static final int CODE_INVALID_RESPONSE_FILE_LENGTH = 5065;
    private static final int CODE_BATCH_IMPORT_LIMIT_EXCEEDED = 5066; // The number of import batch files has exceeded the limit allowed within 24 hours
    private static final int CODE_INVALID_TRANSACTION_TYPE_PRESENT_IN_BATCH_FILE = 5067;
    private static final int CODE_ERROR_PROCESSING_BATCH = 5068;
    private static final int CODE_INVALID_BATCH_IMPORT_REQUEST = 5069; // Only Multipart Form Data request are accepted.
    private static final int CODE_SIGNATURE_ALREADY_IN_SYSTEM = 5070;
    private static final int CODE_SIGNATURE_FORMAT_INVALID = 5071;
    private static final int CODE_SIGNATURE_TYPE_INVALID = 5072; // Signature image type valid values (JPG, GIF, TIF, or PNG).
    private static final int CODE_SIGNATURE_IMAGE_EXCEEDS_SIZE_LIMITATIONS = 5073; // Signature image exceeds the 10K size quota.
    private static final int CODE_SIGNATURE_NOT_ALLOWED_FOR_MARKET_SEGMENT = 5074;
    private static final int CODE_MASTERPASS_WALLET_NOT_AVAILABLE = 5078;
    private static final int CODE_MASTERPASS_NOT_SETUP_FOR_TERMINAL = 5079;
    // 5080 - NOT USED // Values for ssl_3dsecure_value and ssl_xid are required
    // 5081 - NOT USED // Value for ssl_xid is required.
    private static final int CODE_INVALID_DBA_NAME = 5083; // The DBA name cannot contain special characters and based on the DBA prefix setup for your terminal, this value cannot exceed 21 , 17 or 12 characters long
    private static final int CODE_INVALID_TOKEN = 5085; // The token supplied in the authorization request appears to be invalid.
    private static final int CODE_INVALID_CARD_INFORMATION = 5086; // The card information supplied in the authorization request appears to be invalid. You cannot provide both token and card number for processing.
    private static final int CODE_TRANSACTION_CURRENCY_NOT_ALLOWED_FOR_TERMINAL = 5087; // Must setup Multi-currency for terminal
    private static final int CODE_INVALID_TRANSACTION_CURRENCY_FORMAT = 5089; // The transaction currency sent is not correct. Please provide the correct 3-digit ISO code.
    private static final int CODE_INVALID_BIN_OVERRIDE_VALUE = 5090;
    private static final int CODE_INVALID_AMOUNT = 5091;
    private static final int CODE_INVALID_COUNTRY_CODE = 5092;
    private static final int CODE_TRANSACTION_TIME_EXCEEDED = 5093;
    private static final int CODE_INVALID_TRAVEL_INFORMATION = 5094;
    private static final int CODE_INVALID_SEARCH_CRITERIA = 5095; // Too many search criteria were entered for this query. Modify the search and try again.
    private static final int CODE_INVALID_TRANSACTION_CURRENCY = 5096;
    private static final int CODE_MISSING_TRAVEL_INFORMATION = 5097;
    private static final int CODE_CURRENCY_NOT_SUPPORTED = 5098;
    private static final int CODE_INVALID_SEARCH_DATE = 5099; // Search dates must be formatted as MM/DD/YYYY or MM/DD/YYYY hh:mm:ss AM/PM
    private static final int CODE_ACCOUNT_CLOSED = 5100;
    private static final int CODE_ECS_PAPER_CHECK_NOT_SUPPORTED = 5101;
    private static final int CODE_KEYED_CHECK_NOT_ALLOWED_FOR_TERMINAL = 5102;
    private static final int CODE_INVALID_BANK_ACCOUNT_TYPE = 5103; // The value for the check type (ssl_bank_account_type) field should be 1 Numeric Character only. Valid values are: 0 for Personal, 1 for Business.
    private static final int CODE_INVALID_AGREEMENT_INDICATOR_VALUE = 5104; // Valid values are: 1 for Agree, 0 for Do not agree.
    private static final int CODE_INVALID_BANK_ACCOUNT_NUMBER = 5105; // The bank account number must numeric and up to 16 characters long.
    private static final int CODE_INVALID_BANK_ROUTING_NUMBER = 5106; // Bank routing number must be numeric fixed value of 9 characters
    private static final int CODE_INVALID_CHECK_NUMBER = 5107;
    private static final int CODE_MISSING_CHECK_HOLDER_INFO = 5108;
    private static final int CODE_INVALID_MOBILE_INDICATOR = 5121;
    private static final int CODE_INVALID_MERCHANT_IP_ADDRESS = 5122;
    private static final int CODE_EMAIL_NOT_SETUP_FOR_TERMINAL = 5123;
    private static final int CODE_INVALID_POS_ENTRY_MODE_AND_CARD_DATA_COMBO = 5125;
    private static final int CODE_INVALID_MOBILE_SOURCE = 5126;
    private static final int CODE_EMV_NOT_ALLOWED_FOR_CARD_TYPE = 5130; // You can process this card type swiped or keyed.
    private static final int CODE_SWIPE_WITHOUT_FALLBACK_NOT_ALLOWED = 5131; // Chip read must fail before fallback to swipe is allowed. You must attempt to insert card first.
    private static final int CODE_SIGNATURE_NOT_ALLOWED_FOR_CARD = 5131; // Card verification method for this card does not require a signature
    private static final int CODE_INVALID_CARD_TYPE = 5133; // Transaction not supported with this card type.
    private static final int CODE_INVALID_SEARCH_TRANSACTION_TYPE = 5135; // Transaction type provided in the request is not valid. Valid values are: SALE, VOID, FORCE.
    private static final int CODE_INVALID_SEARCH_AMOUNT = 5136;
    private static final int CODE_INVALID_SEARCH_CARD_TYPE = 5137;
    private static final int CODE_INVALID_SEARCH_CARD_BRAND = 5138;

    private static final int CODE_MANUAL_TRANSACTION_DECLINED = 6001;
    private static final int CODE_DECLINED_INVALID_CARD = 6002;
    private static final int CODE_DECLINED_PICK_UP_CARD = 6003;
    private static final int CODE_DECLINED_AMOUNT_ERROR = 6004;
    private static final int CODE_DECLINED_APPL_TYPE_ERROR = 6005; // TODO check with Elavon sale eng what this is
    private static final int CODE_DECLINED = 6006;
    private static final int CODE_DECLINED_HELP = 6007; // TODO what is this?
    private static final int CODE_DECLINED_REQ_EXCEEDS_BALANCE = 6008;
    private static final int CODE_DECLINED_EXPIRED_CARD = 6009;
    private static final int CODE_DECLINED_INCORRECT_PIN = 6010;
    private static final int CODE_DECLINED_INVALID_TERMINAL_ID = 6011;
    private static final int CODE_DECLINED_INVALID_TERMINAL_ID_1 = 6012;
    private static final int CODE_DECLINED_INVALID_TERMINAL_ID_2 = 6013;
    private static final int CODE_DECLINED_INVALID_VOID_DATA = 6014;
    private static final int CODE_DECLINED_MUST_SETTLE_MMDD = 6015;
    private static final int CODE_DECLINED_NOT_ON_FILE = 6016;
    private static final int CODE_DECLINED_RECORD_NOT_FOUND = 6017;
    private static final int CODE_DECLINED_SERV_NOT_ALLOWED = 6018;
    private static final int CODE_DECLINED_SEQ_ERR_PLS_CALL = 6019;
    private static final int CODE_DECLINED_CALL_AUTH_CENTER = 6020;
    private static final int CODE_DECLINED_CALL_REF = 6021;
    private static final int CODE_DECLINED_CVV2 = 6022;
    private static final int CODE_DECLINED_PLS_RETRY = 6023;
    private static final int CODE_GC_ALREADY_ACTIVE = 6024;
    private static final int CODE_GC_REQUEST_EXCEEDS_BALANCE = 6025;
    private static final int CODE_GC_CANNOT_LOAD_SPECIFIED_AMOUNT = 6026;
    private static final int CODE_GC_NOT_ACTIVATED = 6027;
    private static final int CODE_GC_CANNOT_BE_RELOADED = 6028;
    private static final int CODE_DECLINED_INVALID_REG_KEY = 6029;
    private static final int CODE_DECLINED_INVALID_PACKET = 6030;
    private static final int CODE_DECLINED_INVALID_LRC = 6031;
    private static final int CODE_DECLINED_INVALID_RESPONSE = 6032;
    private static final int CODE_DECLINED_INVALID_LRC_IN_REPONSE = 6033;
    private static final int CODE_DECLINED_INVALID_RECORD_NUMBER_IN_RESPONSE = 6034;
    private static final int CODE_SYSTEM_TEMPORARILIY_UNAVAILABLE = 6038;
    private static final int CODE_INVALID_REQUEST_FORMAT = 6042; // XML request is not well-formed or request is incomplete
    private static final int CODE_INVALID_TOKEN_REQUEST = 7055;
}
